import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getSession, Claims } from "@auth0/nextjs-auth0";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = (await getSession())?.user;

  const LoggoutButton = ({ user }: { user: Claims | undefined }) => {
    if (!user) return undefined;

    return <Link href='/api/auth/logout' className='bg-blue-800 p-2 rounded-xl m-2 self-end flex'>
      Log Out
    </Link>
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex fw flex-grow bg-slate-700 justify-end">
          <div className="flex">
            <LoggoutButton user={user} />
          </div>
        </header>
        {children}</body>
    </html>
  );
}
